### ISSUE TITLE
Error when running nosetests from tutorial

### ISSUE THREAD

**Issue by Anders2013** [litaotao/IPython-Dashboard#10]
``` bash
$ nosetests -s dashboard.tests.testCreateData:test_create_mysql_data
```
# 
## ERROR: Failure: SyntaxError (invalid syntax (lexer.py, line 156))

Traceback (most recent call last):
  File "/home/ander/.virtualenvs/py2/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/ander/.virtualenvs/py2/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ander/.virtualenvs/py2/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ander/git/IPython-Dashboard/dashboard/**init**.py", line 41, in <module>
    from .server import views
  File "/home/ander/git/IPython-Dashboard/dashboard/server/views.py", line 10, in <module>
    from .resources.sql import Sql, SqlData
  File "/home/ander/git/IPython-Dashboard/dashboard/server/resources/sql.py", line 10, in <module>
    import sqlparse
  File "/home/ander/.virtualenvs/py2/local/lib/python2.7/site-packages/sqlparse/**init**.py", line 13, in <module>
    from sqlparse import engine
  File "/home/ander/.virtualenvs/py2/local/lib/python2.7/site-packages/sqlparse/engine/**init**.py", line 8, in <module>
    from sqlparse import lexer
  File "/home/ander/.virtualenvs/py2/local/lib/python2.7/site-packages/sqlparse/lexer.py", line 156
    class Lexer(object, metaclass=LexerMeta):
                                 ^
SyntaxError: invalid syntax

---

Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by Anders2013** [comment]
Solved!  my version of sqlparse was updated.
pip install sqlparse --upgrade
