### ISSUE TITLE
Cannot install in python 3 (incompatibility with mysql-python)

### ISSUE THREAD

**Issue by lstavr** [litaotao/IPython-Dashboard#11]
Hi, 

I tried to install the package in my system (Ubuntu 14.04 LTS - Python 3.5) but I got the following error:

Collecting mysql-python==1.2.5 (from ipython-dashboard)
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uac8z9en/mysql-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip-build-uac8z9en/mysql-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'

Apparently this is related to MySQL-python's lack of support for Python 3.

Is there anything I could do about it?

**Comment by litaotao** [comment]
hi, @lstavr , IPython-Dashboard currently only support Python 2.x , thanks. At the late of this month, I'll make it compatible for Python 3.x .

thanks , if you have any ideas or suggestions, feel free to contribute or give issues.

**Comment by Cherkah** [comment]
hi,
i got the above error too on debian.
waiting for the  Python 3.x compatibility... thx

plus would like to know do i must install/run mysql to use IPython-Dashboard? or can i run without it?
what about postgresql?

debian testing (stretch)
python 3.5

**Comment by karelv** [comment]
+1 for this one!

What is current status?

**Comment by Afuuu** [comment]
It is not compatible for Python 3.x today
@litaotao

**Comment by saenznicolass** [comment]
Not compatible with Python 3.7
