### ISSUE TITLE
Unable to Launch on CentOS

### ISSUE THREAD

**Issue by fzeeshan** [litaotao/IPython-Dashboard#7]
[root@sandbox server]# dash-server
Traceback (most recent call last):
  File "/usr/bin/dash-server", line 9, in <module>
    load_entry_point('IPython-Dashboard==0.1.5', 'console_scripts', 'dash-server')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2386, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/lib/python2.7/site-packages/IPython_Dashboard-0.1.5-py2.7.egg/dashboard/**init**.py", line 13, in <module>
    from .conf import config
  File "/usr/lib/python2.7/site-packages/IPython_Dashboard-0.1.5-py2.7.egg/dashboard/conf/config.py", line 44, in <module>
    logger = config_log()
  File "/usr/lib/python2.7/site-packages/IPython_Dashboard-0.1.5-py2.7.egg/dashboard/conf/config.py", line 35, in config_log
    logging.config.fileConfig('dashboard/conf/logging.conf')
  File "/usr/lib64/python2.7/logging/config.py", line 70, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib64/python2.7/logging/config.py", line 106, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'
[root@sandbox server]#

**Comment by saj1919** [comment]
Got the similar issue on Ubuntu 14.04 LTS

saj1919@swapnilj:~/Public/ipython-dashboard$ dash-server 
Traceback (most recent call last):
  File "/home/saj1919/anaconda/bin/dash-server", line 7, in <module>
    from dashboard.server.start import run
  File "/home/saj1919/anaconda/lib/python2.7/site-packages/dashboard/**init**.py", line 13, in <module>
    from .conf import config
  File "/home/saj1919/anaconda/lib/python2.7/site-packages/dashboard/conf/config.py", line 44, in <module>
    logger = config_log()
  File "/home/saj1919/anaconda/lib/python2.7/site-packages/dashboard/conf/config.py", line 35, in config_log
    logging.config.fileConfig('dashboard/conf/logging.conf')
  File "/home/saj1919/anaconda/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/home/saj1919/anaconda/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/home/saj1919/anaconda/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'

**Comment by saj1919** [comment]
@fzeeshan ... Found the solution =>
1) Create "IPython-Dashboard/dashboard/conf/" directory somewhere on the disk.
2) Copy content from github:IPython-Dashboard/dashboard/conf/ to the local disk.
3) Make changes to logger path and redis and mysql settings.
4) Run redis
5)Run dash-server

Working.

@litaotao ... Need to add these steps to installation steps on the main page.

Cheers !!!

**Comment by litaotao** [comment]
@fzeeshan @saj1919 hi, guys, sorry for the lately reply, have been stuck in the big drop of Chinese A shares in the last month, will keep developing this from Feb, thanks a lot. 

I'll take a look at this today, and find a way to make it , thanks again
